server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 920954257bwb?
    url: jdbc:mysql://localhost:3306/代码?useUnicode=true&characterEncoding=utf-8&8allowWMulti

mybatis:
  # 指定 Mapper XML 文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true